# Generated by Django 4.2.1 on 2023-06-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerShipBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='PartnerBrand')),
            ],
        ),
    ]
